export const actionTypes = {
  TODO_APP: {
    CHANGE_CODE: 'TODO_APP_CHAGE_CODE',
    ADD_TODO: 'TODO_APP_ADD_TODO',
    REMOVE_TODO: 'TODO_APP_REMOVE_TODO',
    CHANGE_STATUS: 'TODO_APP_CHANGE_STATUS',
    CLICK_TODO: 'TODO_APP_CLICK_TODO',
    UPDATE_TODO: 'TODO_APP_UPDATE_TODO',
    CHANGE_TODO: 'TODO_APP_CHANGE_TODO'
  }
}
